//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public string FechaSalida { get; set; }
        public string FechaSalidaReal { get; set; }
        public string HoraSalida { get; set; }
        public string HoraSalidaReal { get; set; }
        public string FechaRegreso { get; set; }
        public string FechaRegresoReal { get; set; }
        public string HoraRegreso { get; set; }
        public string HoraRegresoReal { get; set; }
        public string Descripcion { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> Numero { get; set; }
        public string TipoPermiso { get; set; }
        public string Motivo { get; set; }
        public string JefeInmediato { get; set; }
        public string FechaPermiso { get; set; }
    }
}
